# Generated by Django 2.0.3 on 2019-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOBDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(default='ABC123', max_length=20)),
                ('RPM', models.IntegerField(default=0)),
                ('Speed', models.FloatField(default=0)),
                ('FuelTankLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VIN', models.CharField(default='ABC123', max_length=20)),
                ('OwnerFirstName', models.CharField(default='Rajeev', max_length=50)),
                ('OwnerLastName', models.CharField(default='M C ', max_length=50)),
                ('Make', models.CharField(default='Renault', max_length=50)),
                ('Model', models.CharField(default='Duster', max_length=50)),
            ],
        ),
    ]
