# Generated by Django 2.0.3 on 2019-03-22 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carobddata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
