# Generated by Django 2.0.3 on 2019-03-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0005_auto_20190323_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarJSONOBDData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(default=' ', max_length=100)),
                ('VIN', models.CharField(default='VIN1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'CarJSONOBDData',
                'verbose_name': 'CarJSONOBDData',
            },
        ),
    ]
