# Generated by Django 2.0.3 on 2019-03-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0006_carjsonobddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carjsonobddata',
            name='data',
            field=models.CharField(default=' ', max_length=1024),
        ),
    ]
