# Generated by Django 2.1.5 on 2019-03-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0008_auto_20190324_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carjsonobddata',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='carobddata',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='carprofile',
            name='FuelTankVolume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carobddata',
            name='FuelTankLevel',
            field=models.FloatField(default=0),
        ),
    ]
