# Generated by Django 2.1.5 on 2019-03-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0010_delete_carjsonobddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='carobddata',
            name='FuelUsageTrend',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='carobddata',
            name='SecondsElapsed',
            field=models.FloatField(default=0),
        ),
    ]
