# Generated by Django 2.1.7 on 2019-03-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0011_auto_20190330_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carobddata',
            name='SecondsElapsed',
            field=models.FloatField(default=1),
        ),
    ]
