# Generated by Django 2.1.7 on 2019-03-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0012_auto_20190330_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carobddata',
            name='SecondsElapsed',
        ),
    ]
