# Generated by Django 2.1.7 on 2019-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0013_remove_carobddata_secondselapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='carobddata',
            name='FuelUsageDeviation',
            field=models.FloatField(default=0),
        ),
    ]
