# Generated by Django 2.1.7 on 2019-03-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obdService', '0014_carobddata_fuelusagedeviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carobddata',
            name='FuelUsageDeviation',
        ),
        migrations.RemoveField(
            model_name='carobddata',
            name='FuelUsageTrend',
        ),
        migrations.AddField(
            model_name='carobddata',
            name='PossibleFuelLeak',
            field=models.IntegerField(default=0),
        ),
    ]
